kind: pipeline
type: docker
name: test

steps:
  - name: Test Ruby
    image: ruby:3.0.1
    commands:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > "${HOME}/bin/cc-test-reporter"
      - chmod +x "${HOME}/bin/cc-test-reporter"
      - bundle -v
      - bundle install
      - cc-test-reporter before-build
      - bundle exec rake
      - cc-test-reporter after-build --exit-code $? -t simplecov
    environment:
      CC_TEST_REPORTER_ID: 7579537dde1ab4906da756393278a55e18ed1257f4ab6a235aa154fa718fc42a

  - name: Upload to RubyGems
    image: ruby:3.0.1
    commands:
      - gem build ios_config_profile.gemspec
      - gem push -V *.gem
    environment:
      GEM_HOST_API_KEY:
        from_secret: RUBYGEMS_API_KEY
    when:
      event:
        - tag
